server:
    port: 8080
    address: localhost

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_test
        username: root
        password: root

mybatis:
    typeAliasesPackage: com.example.model
    mapperLocations: classpath:/mapper/*.xml
